# Generated by Django 5.2.7 on 2026-01-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracionpago',
            unique_together={('canal', 'cuenta_destino')},
        ),
        migrations.RemoveField(
            model_name='configuracionpago',
            name='medio',
        ),
    ]
