# Generated by Django 5.2.7 on 2026-01-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('requiere_origen', models.BooleanField(default=False)),
                ('requiere_referencia', models.BooleanField(default=False)),
                ('es_egreso', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagofactura',
            name='medio_pago',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='origen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='terminal_pagos.cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='tipo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='terminal_pagos.tipopago'),
            preserve_default=False,
        ),
    ]
