# Generated by Django 5.2.7 on 2026-01-17 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagofactura',
            name='fecha',
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
