# Generated by Django 5.2.7 on 2026-01-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0002_remove_pagofactura_fecha_pagofactura_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofactura',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
