# Generated by Django 5.2.7 on 2025-11-04 01:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0002_alter_transaccion_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_n', models.PositiveIntegerField(blank=True, null=True)),
                ('concepto', models.CharField(choices=[('almacen', 'Compra Almacén - Taller'), ('servicio_taller', 'Servicio Taller'), ('deuda_adicional', 'Deuda Adicional'), ('arrendamiento', 'Tarifa Arrendamiento'), ('empeno', 'Pago Empeño'), ('abono_inicial', 'Abono a Inicial')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('ajuste_pp', 'Ajuste Pico y Placa'), ('comision', 'Comisión')], max_length=20)),
                ('origen_nequi', models.CharField(blank=True, choices=[('transf_nequi', 'Transf Nequi'), ('bancolombia', 'Bancolombia'), ('consignacion', 'Consignación'), ('ptm', 'PTM'), ('transfiya', 'TransfiYa')], max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_pagos.factura')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_pagos.factura'),
        ),
    ]
