# Generated by Django 5.2.7 on 2026-01-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0003_pagofactura_validado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagofactura',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
