# Generated by Django 5.2.7 on 2026-01-29 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_remove_credito_tipo'),
        ('terminal_pagos', '0004_alter_pagofactura_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfactura',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_factura', to='creditos.credito'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='tipo_item',
            field=models.CharField(choices=[('tarifa', 'Tarifa'), ('otro', 'Otro pago'), ('almacen', 'Ítem de almacén'), ('abono_credito', 'Abono a crédito'), ('taller', 'Servicio de taller')], max_length=20),
        ),
    ]
