# Generated by Django 5.2.7 on 2026-02-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0006_factura_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='es_compensacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='referencia_original',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='tipo_item',
            field=models.CharField(choices=[('tarifa', 'Tarifa'), ('multa', 'Pago de multa'), ('otro', 'Otro pago'), ('almacen', 'Ítem de almacén'), ('abono_credito', 'Abono a crédito'), ('taller', 'Servicio de taller')], max_length=20),
        ),
    ]
