# Generated by Django 5.2.7 on 2026-02-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_pagos', '0007_factura_anulada_por_factura_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='tipo_item',
            field=models.CharField(choices=[('tarifa', 'Tarifa'), ('pago_inicial', 'Pago inicial'), ('multa', 'Pago de multa'), ('otro', 'Otro pago'), ('almacen', 'Ítem de almacén'), ('abono_credito', 'Abono a crédito'), ('taller', 'Servicio de taller')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagofactura',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
