# Generated by Django 5.2.7 on 2025-11-11 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_status_alter_cliente_tipo'),
        ('vehiculos', '0002_vehiculo_linea_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('cuota_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dias_contrato', models.PositiveIntegerField()),
                ('visitador', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('vehiculo', models.ForeignKey(limit_choices_to={'estado': 'Inactivo'}, on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo')),
            ],
        ),
    ]
