# Generated by Django 5.2.7 on 2025-12-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], help_text='Motivo del estado inactivo del contrato.', max_length=20, null=True),
        ),
    ]
