# Generated by Django 5.2.7 on 2025-12-15 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0002_contrato_motivo'),
        ('vehiculos', '0004_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='vehiculo',
            field=models.ForeignKey(limit_choices_to={'estado': 'Vitrina'}, on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo'),
        ),
    ]
