# Generated by Django 5.2.7 on 2026-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0004_contrato_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='frecuencia_pago',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dias_contrato',
            field=models.PositiveIntegerField(),
        ),
    ]
