# Generated by Django 5.2.7 on 2026-01-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0005_remove_contrato_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='frecuencia_pago',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', help_text='Frecuencia con la que se generan cobros', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dias_contrato',
            field=models.PositiveIntegerField(help_text='Duración total del contrato en días'),
        ),
    ]
