# Generated by Django 5.2.7 on 2026-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0006_contrato_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='frecuencia_pago',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual')], default='Diario', help_text='Frecuencia con la que se generan cobros', max_length=20),
        ),
    ]
