# Generated by Django 5.2.7 on 2026-02-03 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0007_alter_contrato_frecuencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cuota_inicial_pagada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
