# Generated by Django 5.2.7 on 2026-02-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0008_contrato_cuota_inicial_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='frecuencia_pago',
            field=models.CharField(choices=[('Diario_7', 'Diario (7 días)'), ('Diario_6', 'Diario (6 días)'), ('Diario_5', 'Diario (5 días)'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual')], default='Diario_7', help_text='Frecuencia con la que se generan cobros', max_length=20),
        ),
    ]
