# Generated by Django 5.2.7 on 2025-10-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('propietario', models.CharField(max_length=100)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('actualizacion_soat', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Vitrina', 'Vitrina'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
    ]
