# Generated by Django 5.2.7 on 2025-11-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='linea_gps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
