# Generated by Django 5.2.7 on 2025-12-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_linea_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado_obs',
            field=models.CharField(blank=True, choices=[('Transito/Policia', 'Tránsito / Policía'), ('Hurto', 'Hurto'), ('Siniestro', 'Siniestro'), ('Traspaso Permanente', 'Traspaso Permanente'), ('Otros', 'Otros')], help_text='Observación del estado solo si el vehículo está inactivo.', max_length=30, null=True),
        ),
    ]
