# Generated by Django 5.2.7 on 2025-12-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_estado_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='vehiculos.marca')),
            ],
            options={
                'verbose_name': 'Marca / Serie',
                'verbose_name_plural': 'Marcas y Series',
                'ordering': ['parent__id', 'nombre'],
            },
        ),
    ]
