# Generated by Django 5.2.7 on 2025-12-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='actualizacion_soat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
