# Generated by Django 5.2.7 on 2025-12-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_alter_vehiculo_actualizacion_soat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Vitrina', 'Vitrina'), ('Inactivo', 'Inactivo')], default='Vitirina', max_length=10),
        ),
    ]
