# Generated by Django 5.2.7 on 2025-12-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Vitrina', 'Vitrina'), ('Inactivo', 'Inactivo')], default='Vitrina', max_length=10),
        ),
    ]
