# Generated by Django 5.2.7 on 2026-01-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tecnomecanica',
            field=models.DateField(blank=True, null=True),
        ),
    ]
