# Generated by Django 5.2.7 on 2026-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_vehiculo_tecnomecanica'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
