# Generated by Django 5.2.7 on 2026-02-02 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('total_sistema', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_arqueo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('autorizado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='CierreCajaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50)),
                ('cuenta', models.CharField(max_length=100)),
                ('total_sistema', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_arqueo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reportes.cierrecaja')),
            ],
        ),
    ]
