# Generated by Django 5.2.7 on 2026-02-02 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        ('terminal_pagos', '0007_factura_anulada_por_factura_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecajadetalle',
            name='configuracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='terminal_pagos.configuracionpago'),
            preserve_default=False,
        ),
    ]
