# Generated by Django 5.2.7 on 2026-02-02 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_cierrecajadetalle_configuracion'),
        ('terminal_pagos', '0007_factura_anulada_por_factura_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecajadetalle',
            name='configuracion',
        ),
        migrations.RemoveField(
            model_name='cierrecajadetalle',
            name='cuenta',
        ),
        migrations.AlterField(
            model_name='cierrecajadetalle',
            name='medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terminal_pagos.mediopago'),
        ),
    ]
