# Generated by Django 5.2.7 on 2025-10-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_ref_1', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_ref_2', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('inversionista', 'Inversionista')], default='normal', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('lista_negra', 'Lista Negra')], default='normal', max_length=20, null=True)),
            ],
        ),
    ]
