# Generated by Django 5.2.7 on 2025-11-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Lista Negra', 'Lista Negra')], default='Normal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Inversionista', 'Inversionista')], default='Normal', max_length=20),
        ),
    ]
