# Generated by Django 5.2.7 on 2026-01-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_status_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='costo_administrativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='costo_operativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
