# Generated by Django 5.2.7 on 2025-10-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('utilidad', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso_compra', 'Compra a proveedor'), ('ingreso_devolucion_cliente', 'Devolución cliente'), ('ingreso_ajuste', 'Ajuste ingreso'), ('salida_devolucion_proveedor', 'Devolución a proveedor'), ('salida_cortesia', 'Cortesía'), ('salida_ajuste', 'Ajuste salida'), ('salida_venta', 'Venta')], max_length=30)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_referencia', models.CharField(blank=True, help_text='Factura o documento relacionado (proveedor, cliente, placa, etc.)', max_length=100, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.proveedor')),
            ],
        ),
    ]
