# Generated by Django 5.2.7 on 2025-12-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
