# Generated by Django 5.2.7 on 2025-10-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
