# Generated by Django 5.2.7 on 2025-10-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_producto_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='utilidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
