# Generated by Django 5.2.7 on 2025-10-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_producto_utilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='factura_referencia',
            field=models.CharField(blank=True, help_text='Factura o documento relacionado (proveedor, cliente, placa, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso_compra', 'Compra a proveedor'), ('ingreso_devolucion_cliente', 'Devolución cliente'), ('ingreso_ajuste', 'Ajuste ingreso'), ('salida_devolucion_proveedor', 'Devolución a proveedor'), ('salida_cortesia', 'Cortesía'), ('salida_ajuste', 'Ajuste salida'), ('salida_venta', 'Venta')], max_length=30),
        ),
    ]
