# Generated by Django 5.2.7 on 2025-10-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_movimiento_factura_referencia_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
