# Generated by Django 5.2.7 on 2026-01-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrendamientos', '0007_alter_contrato_frecuencia_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('almacen', 'Artículo de almacén'), ('taller', 'Servicio de taller'), ('efectivo', 'Préstamo de efectivo')], help_text='Tipo de crédito', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Comentario general del crédito (opcional)')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Valor total del crédito', max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Saldo pendiente del crédito', max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha de creación del crédito')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20)),
                ('contrato', models.ForeignKey(help_text='Contrato al que se asocia el crédito', on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='arrendamientos.contrato')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del item', max_length=255)),
                ('cantidad', models.PositiveIntegerField(blank=True, help_text='Cantidad (solo aplica para almacén o taller)', null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitario (solo aplica para almacén o taller)', max_digits=12, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item', max_digits=12)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='creditos.credito')),
            ],
            options={
                'verbose_name': 'Ítem de crédito',
                'verbose_name_plural': 'Ítems de crédito',
            },
        ),
    ]
