# Generated by Django 5.2.7 on 2026-01-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditoitem',
            options={},
        ),
        migrations.AddField(
            model_name='creditoitem',
            name='observacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditoitem',
            name='tipo',
            field=models.CharField(choices=[('almacen', 'Artículo de almacén'), ('taller', 'Servicio de taller'), ('efectivo', 'Préstamo de efectivo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditoitem',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditoitem',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='creditoitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditoitem',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
