# Generated by Django 5.2.7 on 2026-01-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_alter_creditoitem_options_creditoitem_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='tipo',
            field=models.CharField(choices=[('1', 'Artículo de almacén'), ('taller', 'Servicio de taller'), ('efectivo', 'Préstamo de efectivo')], help_text='Tipo de crédito', max_length=20),
        ),
    ]
