# Generated by Django 5.2.7 on 2026-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_alter_credito_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='tipo',
            field=models.CharField(choices=[('almacen', 'Artículo de almacén'), ('taller', 'Servicio de taller'), ('efectivo', 'Préstamo de efectivo')], help_text='Tipo de crédito', max_length=20),
        ),
    ]
