# Generated by Django 5.2.7 on 2026-01-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_alter_credito_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoitem',
            name='observacion',
        ),
    ]
