# Generated by Django 5.2.7 on 2026-01-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_remove_creditoitem_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='tipo',
        ),
    ]
