# Generated by Django 5.2.7 on 2026-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_remove_credito_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20),
        ),
    ]
